version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestPullLDS1Project
  gitServerName: dima
  gitUrl: https://github.com/deemashlayer/TestPullLDS1Project
  gitUsername: deemashlayer
  gitBranch: main
